DROP POLICY IF EXISTS "Public can read relatorios" ON public.relatorios;
DROP POLICY IF EXISTS "Public can insert relatorios" ON public.relatorios;
DROP POLICY IF EXISTS "Public can delete relatorios" ON public.relatorios;
DROP POLICY IF EXISTS "Public can read inadimplentes" ON public.inadimplentes;
DROP POLICY IF EXISTS "Public can insert inadimplentes" ON public.inadimplentes;
DROP POLICY IF EXISTS "Public can delete inadimplentes" ON public.inadimplentes;
DROP POLICY IF EXISTS "Public can read boletos" ON public.boletos;
DROP POLICY IF EXISTS "Public can insert boletos" ON public.boletos;
DROP POLICY IF EXISTS "Public can delete boletos" ON public.boletos;
DROP POLICY IF EXISTS "Public can read processos_judiciais" ON public.processos_judiciais;
DROP POLICY IF EXISTS "Public can insert processos_judiciais" ON public.processos_judiciais;
DROP POLICY IF EXISTS "Public can update processos_judiciais" ON public.processos_judiciais;
DROP POLICY IF EXISTS "Public can delete processos_judiciais" ON public.processos_judiciais;
CREATE POLICY "Auth read relatorios" ON public.relatorios FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert relatorios" ON public.relatorios FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth delete relatorios" ON public.relatorios FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth read inadimplentes" ON public.inadimplentes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert inadimplentes" ON public.inadimplentes FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth delete inadimplentes" ON public.inadimplentes FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth read boletos" ON public.boletos FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert boletos" ON public.boletos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth delete boletos" ON public.boletos FOR DELETE TO authenticated USING (true);
CREATE POLICY "Auth read processos" ON public.processos_judiciais FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert processos" ON public.processos_judiciais FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update processos" ON public.processos_judiciais FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Auth delete processos" ON public.processos_judiciais FOR DELETE TO authenticated USING (true);