// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwngrpxfrrocpdsicinb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bmdycHhmcnJvY3Bkc2ljaW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0OTU1NjIsImV4cCI6MjA5MzA3MTU2Mn0.BZeo2qUquR50q4n7Y724X-meLrwnbLLZwx_kmlB5hBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});